version: "2.0"
services:
  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: rds-testing.cfkkptzwiybb.us-east-1.rds.amazonaws.com <---( RDS End point )
      UPLOAD_LIMIT: 500M
    ports:
      - '0.0.0.0:82:80'
